### ISSUE TITLE
linking without rebuilding

### ISSUE THREAD

**Issue by martunta** [DimiMikadze/create-react-library#11]
is it possible to somehow link npm module created by create-react-library, so I would not need to run yarn build every time I make any changes in library, so they would appear in the apps that include the module?

**Comment by Bagera** [comment]
I'm not sure I'm the one to comment here but...
Every time you mabe any changes to your library you have to build to transpile the es2015+ to es5 and that is what is used by your other apps.
### Possible fixes:
- You could probably make a es2015+ library without transpiling (but I think that falls outside the scope of this repo) and just import that.
- You could make new scripts like `npm run dev-build` where you make something that watches the `src/` and runs build when you make a change. Then make a PR and might get into the repo so I can use it :)
- Probably smarter ideas

**Comment by Bagera** [comment]
To use the module without having to build every time just add `"module": "src/lib/index.js",` to your package.json
**Warning!** This will break compatibility with Create-react-app as it does not support es2015+ in linked modules.
This obviously only works if you are symlinking or similar, not for a library on npm.
