### ISSUE TITLE
Can't import an image

### ISSUE THREAD

**Issue by lightninglu10** [DimiMikadze/create-react-library#12]
Hey guys, with the current dev webpack config, I can't import an image. It shows up as a data string that doesn't have any image output.

I changed the webpack.dev to the same as create-react-app and importing images in components work.

**Comment by DimiMikadze** [comment]
@lightninglu10 Hi, thanks for reporting.

Can you send PR for fixing this issue?

Anyway in the next week, we are going refactor this library to be global NPM package and this bug will be also fixed.

**Comment by lightninglu10** [comment]
Hey I'm trying to submit a PR, but it won't let me push to this repo.

**Comment by lightninglu10** [comment]
any update here? push access seems not allowed.

**Comment by DimiMikadze** [comment]
@lightninglu10 you can't push to directly to master, create new branch and send PR

**Comment by lightninglu10** [comment]
I did, I tried to push to a new branch but it won’t let me.

**Comment by mfyuce** [comment]
Hi All,

Just sent a pull request for fixing the issue. 

All the best.

**Comment by rtmalone** [comment]
@mfyuce I looked at your PR, does it make sense to utilize `static/**/...` so that however someone prefers to label/build their static dir structure, it'll still pick up the files?

I copied the `src` from one of my projects into this and I noted I had to either create the media dir or modify the webpack config myself to pick up my images.

**Comment by DimiMikadze** [comment]
HI guys,

We have updated our library with new version of `create-react-app` so importing files inside components works exactly as in `cra`

i'm closing this issue right now, because it's being resolved, but feel free to re open it, if needed
