### ISSUE TITLE
how to import into github && update CRL

### ISSUE THREAD

**Issue by talkingtab** [DimiMikadze/create-react-library#17]
The library is great! Thanks for all the work. 

My github project is basic-react-router

I'm trying to use CRL in a way that is similar to react-under-construction demo. I want to have my whole project in github so that someone can clone it, run, build, etc. I know you are tracking create-react-app so I assume CRL will change because of CRA and then my project should change because of your changes. I don't know how that should happen. Is there a way to update CRL?  

Just trying to understand how this should work. Thanks

**Comment by DimiMikadze** [comment]
Hi @talkingtab thanks for the question.

Since `create-react-library` is not an NPM package, I think there's only one way: pull new version of `CRL`, replace `src` folder and `package.json` file.
