### ISSUE TITLE
How to delete src/demo folder

### ISSUE THREAD

**Issue by srivasd** [DimiMikadze/create-react-library#25]
Hi, I am using your example library in order to do an university project. In order to publish it into NPM I need to delete the src/demo folder and I am in trouble with it because I am not too good with webpack. It requires me not to delete the index.js. What I need to do in order to delete that folder?
Thanks.

**Comment by fmilani** [comment]
Hi @srivasd 

I also used create-react-library to publish a library to npm and I didn't have to delete my src/demo folder, npm will ignore it. Could you be more specific on what trouble you're having?
