### ISSUE TITLE
Relative URLs in built CSS are not right

### ISSUE THREAD

**Issue by Bagera** [DimiMikadze/create-react-library#26]
I don't know if this is me but I can't figure out my bug in that case.

I have a component that has CSS linking an image like: `background-image: url('./image.jpg');`
When I build my library the CSS gets transpiled to: `background-image: url('media/image.jpg');`
But the image is copied to a folder called media in the build folder so the is like this:

build/
  css/
    index.css
    ...
  media/
    image.jpg
    ...

So the correct URL should be '../media/image.jpg'.

It's probably a small fix but I'm no webpack guru so I cant make a PR for it.

**Comment by DimiMikadze** [comment]
@Bagera 

Hi, thanks for pointing out this issue.

I'm very busy right now, i'll be able to look on it, by the end of the week. Meanwhile if anyone can fix it, PR will be much appreciated.

**Comment by Bagera** [comment]
@DimiMikadze Have you checked my PR? I think it fixes it without any side effects.

**Comment by filgaia** [comment]
Hi @Bagera I try your fix, but I still have problems when I use the library in a proyect. It doesn't update the hash in the css files. Any suggestions?

**Comment by Bagera** [comment]
@filgaia Do mean when you include a small image that should be Base64 encoded? I have no such files in my project so it may have gone by unnoticed. I could check a bit.
