### ISSUE TITLE
Change server port

### ISSUE THREAD

**Issue by Bagera** [DimiMikadze/create-react-library#31]
Would it be a good idea to change the server port?
I'm testing this on my project.
That way I can have both this and CRA dev servers up at the same time.
I still have to build after changes but at least I don't have to shut the CRA server down every time.

I guess this is a bit specific. It's just for CRA development with a linked CRL.

**Comment by DimiMikadze** [comment]
@Bagera 

Hi,  you can always change port in `CRA` or in `CRL` project by editing `start` command in `package.json`.

Linux / Mac:
- `"start": "PORT=3006 react-scripts start"` or `"start": "export PORT=3006 react-scripts start"`

Windows:
- `"start": "set PORT=3006 && react-scripts start"`

**Comment by Bagera** [comment]
Yeah I did this. Just a thought I had, but as I said it was a bit specific for my project and as you point out, it's easy to do.
