### ISSUE TITLE
Why is /build ignored?

### ISSUE THREAD

**Issue by paulintrognon** [DimiMikadze/create-react-library#36]
In your example component (react-under-construction), your /build folder is not ignored. That is making sense to me as you would need that folder to be copied when you add the repo as a dependency in you package.json.

Then why is the build folder ignored in this repo?

**Comment by DimiMikadze** [comment]
@paulintrognon Hi, build folder is ignored from `Git` not from `NPM` so you can push build folder directly to NPM.

**Comment by ronaiza-cardoso** [comment]
Hi, when I publish my project the build folder is not get sending to the npm.

![image](https://user-images.githubusercontent.com/7999914/52419338-c5737180-2ae7-11e9-9120-b64beb6728f0.png)
This are the files that are published when I run `npm run publish` from the demo, where is the build files?
