### ISSUE TITLE
Can't resolve 'create-react-library' when using `npm link`

### ISSUE THREAD

**Issue by MrJadaml** [DimiMikadze/create-react-library#37]
I am having troubles symlinking this library into another react application. From this application I run `npm link` and then in the other react application I run `npm link create-react-library`. 

I then try to import in a component with `import Example from 'create-react-library';` but get the following error:  

`Module not found: Can't resolve 'create-react-library' in '/home/bob/apps/myApp/src'`

If I run `npm list -g --depth=0` I see that the CRL symlink lives there.

**Comment by colejoh** [comment]
I also get this error.

**Comment by wwan5803** [comment]
I also got this error, however, you can just write and test the demo project inside the library project without using npm link.

**Comment by hodgef** [comment]
You can do `npm instal [path to your local library dir]` instead. Works for me !
