### ISSUE TITLE
Module not found: Can't resolve 'reactDOM' in '*\my-package\build'

### ISSUE THREAD

**Issue by Nerdy-Girl** [DimiMikadze/create-react-library#4]
after building and publishing into npm i get this error while importing component from my package into another project:

Failed to compile
./node_modules/freightable-library/build/index.js
Module not found: Can't resolve 'reactDOM' in 'C:\*\my-package\build'
This error occurred during the build time and cannot be dismissed.

Help please!

**Comment by DimiMikadze** [comment]
Hi @CodeMeNatalie 

do you have `react` and `react-dom` as dependencies in app where you are importing your library?

**Comment by Nerdy-Girl** [comment]
Yes

**Comment by DimiMikadze** [comment]
@CodeMeNatalie can't help without seeing project or code samples itself, maybe you'll take a look at example library built with this starter? https://github.com/UdiliaInc/react-under-construction

**Comment by geohuz** [comment]
I have the same issue. Can't find a solution.

**Comment by untemps** [comment]
You have to fix the 'externals' configuration in webpack.config.prod.js :

```
externals: {
   'react': 'react',
   'react-dom': 'react-dom'
}
```

**Comment by DimiMikadze** [comment]
@untemps thanks, updated!
