### ISSUE TITLE
How can I publish the library to be used in browser (as UMD module ?! )

### ISSUE THREAD

**Issue by ieugen** [DimiMikadze/create-react-library#41]
Hello, 

I wish to publish my library to be used in browser. How can I do that? 
It would be great if this was added to the documentation.

Thanks,

**Comment by DimiMikadze** [comment]
Hi, this library is intended to create NPM packages, ( React NPM library starter kit ) and it's definitely for browser since it's React.

Without NPM i've never tried to use library built with this starter kit, but maybe try to load React and ReactDom first and then load your bundle?

**Comment by ieugen** [comment]
Thanks, we chosed to use nwb. It has OOTB umd module publishing.

**Comment by mwarger** [comment]
@ieugen In case it's any help, you can modify the rollup config to output a UMD by adding this to the output:

```
...
output: [
    {
      file: pkg.main,
      format: 'umd',
      sourcemap: true,
      name: 'exampleComponent'  // this name is how the component is referenced in javascript
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true
    }
  ],
```
