### ISSUE TITLE
How can update to latest version of create-react-app

### ISSUE THREAD

**Issue by zahidraza** [DimiMikadze/create-react-library#42]
New version of create-react-app (v1.1.5) is available. how can we update to new version. If some doc will be there, it would be very helpful.

**Comment by DimiMikadze** [comment]
Hi, unfortunatelly you can’t update it automatically, i have to see whats new and then rebase it with new version. 

Btw is there any specific reason you want to upgrade to 1.15 version, because after seeing changelog i can’t see any new feature in there

**Comment by grubersjoe** [comment]
I know it's probably a lot of work to upgrade and it was released very recently, but v2 of CRA is out now. It would be really nice to have all the new features like Babel 7, CSS modules etc. in this project as well.

Can we expect an upgrade soon :)? Thank you for maintaining this repository. It's very helpful.

**Comment by DimiMikadze** [comment]
Hi @grubersjoe, thanks for the comment. I'll try to upgrade it in the next week :)

**Comment by hodgef** [comment]
Would also be interested in this new version, thank you for the amazing work. DependaBot could also be added to keep the dependencies in check: https://dependabot.com/

**Comment by tdiluzio** [comment]
Hi is the upgrade done? If not I volunteer

**Comment by DimiMikadze** [comment]
@tdiluzio it's not, sorry i got super busy last weeks. feel free to volunteer, it would be awesome! :)

**Comment by tdiluzio** [comment]
Ok I'll do that @DimiMikadze

**Comment by hodgef** [comment]
Hi create-react-library mantainers,

I created my own repo to support CRA v2+ (needed it asap for my projects). Feel free to take the changes in there and integrate them to create-react-library as needed.

https://github.com/hodgef/js-library-boilerplate

Regards

**Comment by panz3r** [comment]
Hi,

I just submitted a PR (#64) to add a simple guide on how to upgrade a project using `create-react-library` as a starting point and also how to upgrade `create-react-library` itself, hoping that the process will be easier for everyone to do.
