### ISSUE TITLE
Help me regarding prop-types

### ISSUE THREAD

**Issue by NomanGul** [DimiMikadze/create-react-library#46]
Can I use Prop-types as a devDependency and Publish my library on npm??? Would prop-types work as a devDependency in production?

**Comment by mohsinulhaq** [comment]
`prop-types` should be a dependency https://github.com/facebook/prop-types/issues/4
dev-dependencies don't get installed when people `npm install` your library.

If you don't want to ship it, then you could use https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types babel plugin to remove it's usage from your build.

**Comment by mohsinulhaq** [comment]
`prop-types` should be a dependency https://github.com/facebook/prop-types/issues/4
dev-dependencies don't get installed when people `npm install` your library.

If you don't want to ship it, then you could use https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types babel plugin to remove its usage from your build.
