### ISSUE TITLE
Identify non-default component

### ISSUE THREAD

**Issue by wangdicoder** [DimiMikadze/create-react-library#5]
Hi, thanks for providing this such useful repository. Actually, it's fine to export only a default component, but how to make the IDE identify those non-default components? For example, your default code provides two components, where one is called Example, and the other is SecondExample. If I push them onto the NPM, when I pull the package, the IDE could not automatically detect the SecondExample component although it works. Is it possible to setup something to solve this situation?

**Comment by DimiMikadze** [comment]
Hi @wangdicoder, sorry for late answer.

I don't know to be honest, currently i'm not using any IDE just sublime text :)
