### ISSUE TITLE
Getting Error From Published Package

### ISSUE THREAD

**Issue by bvmcode** [DimiMikadze/create-react-library#56]
https://github.com/bvmcode/react-list-items

Thanks for your repo. I followed it from start to end. I installed my published package to test it in a project and in the very simple test I get an error. 

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `App`.

When I remove my component from this test project I get no error so it for stemming from the published package. Any insight on this would be appreciated. thanks

**Comment by bvmcode** [comment]
nevermind, my index.js was the problem

**Comment by grubersjoe** [comment]
Do you still remember what the issue was? I'm having the same problem right now and can't find the solution. I do export a regular React component.
