### ISSUE TITLE
index.html in demo directory does not include built JS and CSS

### ISSUE THREAD

**Issue by grubersjoe** [DimiMikadze/create-react-library#59]
I tried to build the demo in the current master by running `yarn demo`  and to my surprise the `index.html` file does not include the `<script>` and `<link>` tags required to load the built JS and CSS code.

I have a [small React component](https://github.com/grubersjoe/react-github-calendar), which is based on an earlier version of `create-react-library` (CRA v1) and it used to work. So I fear, something broke in between...

The HTML file seems untouched. It looks like this in the `demo` directory after building:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
    <title>React App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>          
```

Thank you for all the work and maintaining this library!

**Comment by siansell** [comment]
Just discovered the same thing.

The webpack config [doesn't include HtmlWebpackPlugin](https://github.com/DimiMikadze/create-react-library/blob/master/config/webpack.config.js#L488) or [InterpolateHtmlPlugin](https://github.com/DimiMikadze/create-react-library/blob/master/config/webpack.config.js#L525) in the demo environment. 

I'd make a PR but [package.json homepage](https://github.com/DimiMikadze/create-react-library/blob/master/package.json#L20) also needs setting appropriately or removing for a demo build. Also react and react-dom are listed as externals in the demo env so not included in the built files.

[Here's a branch](https://github.com/siansell/create-react-library/tree/fix-demo-build) with a potential fix.

**Comment by panz3r** [comment]
Hi @grubersjoe  ,

I just submitted a PR (#63) to update it to the latest available version of `create-react-app` (currently `v3.1.2`) and fix the issue you reported above.

As stated by @siansell the `webpack.config` file had some issues when used for the `demo` env (my bad actually, I missed them when upgrading to `create-react-app` v2).
