### ISSUE TITLE
Generating a production versione of the demo app

### ISSUE THREAD

**Issue by keul** [DimiMikadze/create-react-library#6]
(First of all, let me thank you for this repo, really helpful)

I think it will be *really* helpful to be able to generate a build version of the demo app (`npm run build_demo`), to be easily used in a github.io page as an online live demo.

**Comment by DimiMikadze** [comment]
Hey @keul  thanks!

can you send PR for that?

**Comment by keul** [comment]
@DimitriMikadze sure, can try to work on this in few days
