### ISSUE TITLE
Production build give error: TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by danydhondt** [DimiMikadze/create-react-library#69]
I am using this library template for all my libraries.
Suddenly, my last library gave this `Super expression must either be null or a function, not undefined` error.

- I could build the library without any problem
- I could import the library in a CRA project and run it without any problem
- But when I made a production build and uploaded that to the server, the problem occurred.

After a few days of struggling, I decided to delete the `config`and `scripts` folder of my library and replaced those with versions of another library of a few weeks ago. So the versions of one of your previous commits.

I think a tweak in one of those files is causing this problem.

I'm not a Webpack or configuration expert so I can't help you on that BUT I found out something that might help you:

I made a fresh library using your new npx command

Doing the whole process of building it and using that in my CRA project, **all went fine!**
In your project, you have 2 example files, both of them functional components.
I changed one of them to a class component, thus extending `React.Component` and then, the error occurred!

So I suggest that you add at least one class component to you template.

It's probably a very small tweak for you, but people who use your (excellent) library **will** bounce into the same problem.

**Comment by danydhondt** [comment]
this might help? https://github.com/airbnb/react-with-styles/issues/151

**Comment by DimiMikadze** [comment]
Hi @danydhondt I just refactored `Example` component to Class based component and it worked and was built as expected, maybe this will help you? https://stackoverflow.com/questions/30116430/reactjs-giving-error-uncaught-typeerror-super-expression-must-either-be-null-or

I'm not converting default example components to Class based components, since React Hooks came out.

Let me know how it goes 👍

**Comment by danydhondt** [comment]
Thx @DimiMikadze . I read that article but it didn't help me. I'll try to isolate even more and I'll come back here with my findings. Thx

**Comment by danydhondt** [comment]
I've set up a project trying to recreate this problem but everything went ok. The problem must be somewhere deep in my code. I'll close this for now. When I manage to find the problem in the near future, I'll reopen this. Thanks @DimiMikadze for your help anyway. And thanks for this great library builder!
