### ISSUE TITLE
usage of the app?

### ISSUE THREAD

**Issue by adamchenwei** [DimiMikadze/create-react-library#7]
I am a bit confused... are we pretty much just clone the whole app to use it or we do something like

`npm install -g create-react-library`

then do

`create-react-library my-new-lib`

Is that how this thing work? Would be nice to update readme if it is but if not plz let me know thanks! Pretty awesome concept!

**Comment by arowshan** [comment]
I think the Getting Started documentation explains this better, but yea you clone the app and place your library in lib.

**Comment by DimiMikadze** [comment]
@adamchenwei you have to clone it.

It's explained in readme file at `Getting started` section

https://github.com/UdiliaInc/create-react-library#getting-started
