### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by cichy** [DimiMikadze/create-react-library#72]
**Describe the topic**
I published on netlify but a page is blank. log TypeError: Cannot read property 'replace' of undefined". 
A clear and concise description of what the topic is.

**Your suggestions for this topic**

Clear and simple suggestions for how you think this should be handled.

**Screenshots**

If applicable, add screenshots to help explain your points.

**Code snippets**

If applicable, add code samples to help explain your points.

**Additional context**

**Comment by DimiMikadze** [comment]
@cichy those issue template headings are the tips how you can describe your issue, so people can understand your concern and be able to help you.
