### ISSUE TITLE
Exporting css

### ISSUE THREAD

**Issue by danydhondt** [DimiMikadze/create-react-library#75]
In my library I create a css file to style my components. When I run the demo, my components style correctly. 
However, when I build my library and import a component in the consuming app, the component isn't styled. 
Probably I'm doing something wrong but I haven no idea what that could be.

**Comment by DimiMikadze** [comment]
Hi, you need to explicitly require CSS file from the library, since it's not bundled with Javascript code during the build.

`import {libraryName}/index.css`

**Comment by danydhondt** [comment]
Thanks DimiMikadze! will try that
